# Generated by Django 2.1.7 on 2019-03-22 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicklerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickler_text', models.TextField(max_length=4000)),
                ('update_count', models.IntegerField(verbose_name=0)),
                ('next_update_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete='CASCADE', related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
