# Generated by Django 2.1.7 on 2019-03-29 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickleritem',
            name='update_count',
        ),
        migrations.AlterField(
            model_name='tickleritem',
            name='created_by',
            field=models.ForeignKey(on_delete='CASCADE', related_name='tickler_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
