# Generated by Django 2.1.7 on 2019-03-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20190329_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickleritem',
            name='created_by',
        ),
    ]
