# Generated by Django 2.1.7 on 2019-03-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_tickleritem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickleritem',
            name='completed_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
