# Generated by Django 2.1.7 on 2019-04-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_tickleritem_completed_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickleritem',
            name='tickler_text',
            field=models.TextField(max_length=4000, unique=True),
        ),
    ]
