# Generated by Django 2.1.7 on 2019-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20190403_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickleritem',
            name='hidden_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
