# Generated by Django 2.1.7 on 2019-04-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_tickleritem_hidden_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickleritem',
            name='tickler_text',
            field=models.TextField(max_length=4000),
        ),
    ]
