# Generated by Django 2.1.7 on 2019-04-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20190410_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicklerItem',
            new_name='TaskItem',
        ),
        migrations.RenameField(
            model_name='taskitem',
            old_name='tickler_text',
            new_name='task_text',
        ),
    ]
