# Generated by Django 2.1.7 on 2019-04-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20190411_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskItem',
            new_name='TaskModel',
        ),
    ]
