# Generated by Django 2.2 on 2019-05-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_auto_20190411_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='project',
            field=models.TextField(default='', max_length=400),
        ),
    ]
