# Generated by Django 2.2 on 2019-09-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_auto_20190510_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='why',
        ),
    ]
